language: ruby
rvm:
  - 3.0.0
cache: bundler
dist: focal

branches:
  only:
  - main

script: bundle exec jekyll build

deploy:
  provider: pages
  local-dir: ./_site
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
