title:               Atin Bainada
tagline:             A nobody
description:         Desc
baseurl:             ""
url:                 ""

links:
  home:              /
  projects:          /projects/
  resume:            /resume/
  cv-short:          /resume/1pg/
  cv-long:           /resume/2pg/
  about:             /about/
  

# Navigation links
nav-links:
  - title:           Home
    href:            /
  - title:           Projects
    href:            /projects/
  - title:           Resume
    href:            /resume/
    sublinks:
    - title:         1 page
      href:          /resume/1pg.pdf/
    - title:         2 page
      href:          /resume/2pg.pdf/
  - title:           About me
    href:            /about/



# Social Links
social-links:
  github:            atin
  linkedin:          atin

author:
  name:              Atin Bainada
  url:               atin.github.io
  email:             atinbainada@iitb.ac.in

# Custom vars
avatar:
  normal:            "/img/avatar.png"
  with_mask:         "/img/avatar_with_mask.png"
version: 0.0.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Dependencies
# markdown:            kramdown
# highlighter:         rogue
# permalink:           pretty
# paginate:            5
# paginate_path:       "/blog/page:num/"
# plugins:
#   - jekyll-paginate
# gems:
#     - jekyll-redirect-from
