title:               Atin Bainada
tagline:             A nobody
description:         Desc
baseurl:             ""
url:                 ""

links:
  home:              /
  projects:          /projects/
  resume:            /resume/
  cv-short:          /resume/1pg/
  cv-long:           /resume/2pg/
  about:             /about/


# Navigation links
nav-links:
  - title:           Home
    url:            /
  - title:           Projects
    url:            /projects/
  - title:           Resume
    url:            /resume/
    sublinks:
    - title:         1 page
      url:          /resume/1pg.pdf/
    - title:         2 page
      url:          /resume/2pg.pdf/
  - title:           About me
    url:            /about/



# Social Links
social-links:
  - url:            http://github.com/atin
    icon:           /img/GitHub/PNG/GitHub-Mark-32px.png
  - url:            http://linkedin.com/in/atin
    icon:           /img/GitHub/PNG/GitHub-Mark-32px.png
  - url:            https://stackoverflow.com/users/12011589/at-in
    icon:           /img/icons/stackoverflow.svg
  - url:            https://www.kaggle.com/atin10
    icon:           /img/icons/mathexchange.png

author:
  name:              Atin Bainada
  url:               atin.github.io
  email:             atinbainada@iitb.ac.in

# Custom vars
avatar:
  normal:            /img/avatar.png
  with_mask:         /img/avatar_with_mask.png
version: 0.0.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Dependencies
# markdown:            kramdown
# highlighter:         rogue
# permalink:           pretty
# paginate:            5
# paginate_path:       "/blog/page:num/"
# plugins:
#   - jekyll-paginate
# gems:
#     - jekyll-redirect-from
