title:               Atin Bainada
tagline:             A nobody
description:         Desc
baseurl:             ""
url:                 ""

# Navigation links
nav-links:
  - title:           Home
    href:            /
  - title:           Projects
    href:            /projects/
  - title:           Resume
    sublinks:
    - title:         Short resume
      href:          /resume/1pg.pdf/
    - title:         Long resume
      href:          /resume/2pg.pdf/
    - title:         Very long resume
      href:          /resume/
  - title:           About me
    href:            /aboutme/

# Social Links
social-links:
  github:            atin
  linkedin:          atin

author:
  name:              Atin Bainada
  url:               atin.github.io
  email:             atinbainada@iitb.ac.in

# Custom vars
avatar:
  normal:            "/img/avatar.png"
  with_mask:         "/img/avatar_with_mask.png"
version: 0.0.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Dependencies
# markdown:            kramdown
# highlighter:         rogue
# permalink:           pretty
# paginate:            5
# paginate_path:       "/blog/page:num/"
# plugins:
#   - jekyll-paginate
# gems:
#     - jekyll-redirect-from
